"""
Task-Stratified QA Sampler for joint E2E + Graph QA training.

The active graph-QA ablation is policy-oriented rather than generic graph
understanding: keep QA supervision focused on robot parallel-action selection.
Legality/path questions are useful diagnostics, but they over-teach "what not
to do" and made the E2E policy more conservative in tiny ablations.
"""
from __future__ import annotations

import hashlib
import json
import os
import random
from collections import defaultdict
from pathlib import Path
from typing import Dict, List


REASONING_TYPES = [
    "frontier_next",
    "blocked_by",
    "after_current_complete",
    "ordered_future_path",
    "and_or_feasibility",
    "parallel_independent",
    "parallel_robot_action",
    "thread_of",
]
PERCEPTION_TYPES = ["current_step", "done_count", "future_count"]
CORE_TYPES = REASONING_TYPES + PERCEPTION_TYPES
# Sampling modes for graph QA ablations.
# - parallel_policy_only: direct robot parallel-action supervision, including
#   explicit "no safe parallel action" negatives generated by graph_qa.py.
# - uniform_all_types: every available QA type receives equal budget, testing
#   whether broad graph grounding helps beyond policy-only QA.
# - policy_heavy_mixed: 50% direct policy QA, 50% broad graph-understanding QA.
PARALLEL_POLICY_TYPES = {
    "parallel_robot_action",
}

UNIFORM_ALL_TYPES = {
    "frontier_next",
    "blocked_by",
    "after_current_complete",
    "ordered_future_path",
    "and_or_feasibility",
    "parallel_independent",
    "parallel_robot_action",
    "thread_of",
    "current_step",
    # DAA-v1 decision-aligned types (hyphen format)
    "saved-binary",
    "which-thread-now",
    "frontier-rank",
    "blocked-by",
    # W2t frontier-thread curriculum
    "which-thread-frontier",
    "cross-thread-or-wait",
    # HGQA2 APA-aligned action-selection QA (answers in apa_parallel space)
    "next-action-apa",
    "counterfactual-unlock",
    "updated-state-apa",
    "evidence-executable",
    "frontier-pick-on-thread",
}

DLV3_YAML_TYPES = {
    "counterfactual-unlock",
    "updated-state-apa",
    "next-action-apa",
    "frontier-pick-on-thread",
    # y4: synthesized from state annotations, no graph in prompt
    "y4_status_recovery",
}
DLV3_YAML_WEIGHTS = {
    "counterfactual-unlock": 0.40,
    "updated-state-apa": 0.40,
    "next-action-apa": 0.35,
    "frontier-pick-on-thread": 0.25,
    # y4 weighted equal to y2 (counterfactual-unlock); normalized by sampler
    "y4_status_recovery": 0.40,
}

POLICY_HEAVY_NON_POLICY_TYPES = sorted(UNIFORM_ALL_TYPES - PARALLEL_POLICY_TYPES)
POLICY_HEAVY_WEIGHTS = {
    "parallel_robot_action": 1.0,
    **{t: 1.0 / max(1, len(POLICY_HEAVY_NON_POLICY_TYPES)) for t in POLICY_HEAVY_NON_POLICY_TYPES},
}

# Backwards-compatible exports used by quick diagnostics.
POLICY_QA_TYPES = PARALLEL_POLICY_TYPES
TYPE_WEIGHTS = {
    "parallel_robot_action": 1.0,
}
MANDATORY_DECISION_TYPES = ["parallel_robot_action"]



_QA_TYPE_ALIASES = {
    "y1": "next-action-apa",
    "y2": "counterfactual-unlock",
    "updated": "updated-state-apa",
    "updated_state": "updated-state-apa",
    "updated-state-apa": "updated-state-apa",
    "y3": "frontier-pick-on-thread",
    # y4: counterfactual-free status-recovery question, forced subgraph_mode=none
    "y4": "y4_status_recovery",
    "y4_graphoff": "y4_status_recovery",
    "y4_status_recovery": "y4_status_recovery",
    "next-action-apa": "next-action-apa",
    "counterfactual-unlock": "counterfactual-unlock",
    "frontier-pick-on-thread": "frontier-pick-on-thread",
}


def _apply_qa_types_env(allowed_types, type_weights, mandatory_types):
    """Optional QA_TYPES env filter (e.g. QA_TYPES=y3 / y2,y3 / next-action-apa).

    Restricts an already-resolved (allowed_types, type_weights, mandatory_types)
    triple to the requested subset. No-op when QA_TYPES is unset/empty.
    """
    raw = os.environ.get("QA_TYPES", "").strip()
    if not raw:
        return set(allowed_types), dict(type_weights), list(mandatory_types)
    wanted = []
    for tok in raw.replace(",", " ").split():
        key = tok.strip().lower()
        if not key:
            continue
        wanted.append(_QA_TYPE_ALIASES.get(key, key))
    wanted_set = set(wanted) & set(allowed_types)
    if not wanted_set:
        raise ValueError(
            "QA_TYPES=%r produced no valid types within %s" % (raw, sorted(allowed_types))
        )
    new_weights = {t: w for t, w in type_weights.items() if t in wanted_set}
    if not new_weights:
        new_weights = {t: 1.0 for t in wanted_set}
    new_mandatory = [t for t in mandatory_types if t in wanted_set]
    return set(wanted_set), new_weights, new_mandatory


def _mode_config(sampling_mode: str):
    mode = str(sampling_mode or "parallel_policy_only").strip().lower()
    if mode in {"parallel_policy", "parallel_policy_only", "policy_only"}:
        return mode, set(PARALLEL_POLICY_TYPES), {"parallel_robot_action": 1.0}, ["parallel_robot_action"]
    if mode in {"uniform", "uniform_all", "uniform_all_types", "all_uniform"}:
        weights = {t: 1.0 for t in UNIFORM_ALL_TYPES}
        return mode, set(UNIFORM_ALL_TYPES), weights, sorted(UNIFORM_ALL_TYPES)
    if mode in {"policy_heavy", "policy_heavy_mixed", "mixed_policy_heavy"}:
        return "policy_heavy_mixed", set(UNIFORM_ALL_TYPES), dict(POLICY_HEAVY_WEIGHTS), ["parallel_robot_action"]
    if mode in {"dlv3_yaml", "dlv3qa_yaml", "dlv3_qa_yaml"}:
        _allowed, _weights, _mand = _apply_qa_types_env(
            set(DLV3_YAML_TYPES), dict(DLV3_YAML_WEIGHTS), sorted(DLV3_YAML_TYPES)
        )
        return "dlv3_yaml", _allowed, _weights, _mand
    raise ValueError(f"Unknown QA sampling mode: {sampling_mode}")


def _group_qa_by_task(qa_data: list) -> Dict[str, list]:
    by_task: Dict[str, list] = defaultdict(list)
    for entry in qa_data:
        by_task[entry["task_name"]].append(entry)
    return dict(by_task)


def _progress_bucket(entry: dict) -> str:
    # Prefer explicit future/current state length over total graph size: this is
    # only a sampling bucket, not a graph metric.
    completed = len(entry.get("completed_steps", []) or [])
    if completed < 2:
        return "early"
    if completed < 6:
        return "mid"
    return "late"

# Y4 status-recovery question templates (no graph context in prompt).
_Y4_Q_TEMPLATES = [
    "Based on the video and dialogue history, which steps have been completed in {task}? What is the current status?",
    "What is the current status of {task!r} based on the video and dialogue history? Which steps have already been done?",
]


def _build_none_item(state: dict) -> dict:
    """Build a y4_status_recovery QA pair synthesized from state annotations.

    Forces subgraph_mode=none — no graph image or text is injected into the
    prompt.  The answer is derived directly from completed_steps / current_step
    fields present in every state dict loaded from the QA JSON.
    """
    task = state.get("task_name", "the current task")
    completed = state.get("completed_steps") or []
    current = state.get("current_step") or "unknown"
    tmpl_idx = len(completed) % len(_Y4_Q_TEMPLATES)  # deterministic per state
    question = _Y4_Q_TEMPLATES[tmpl_idx].format(task=task)
    if completed:
        done_str = "; ".join(str(s) for s in completed)
        answer_text = f"Completed steps: {done_str}. Currently doing: {current}."
    else:
        answer_text = f"No steps completed yet. Currently doing: {current}."
    return {
        "task_name": task,
        "current_step": current,
        "completed_steps": list(completed),
        "question": question,
        "options": [],
        "answer": None,
        "answer_text": answer_text,
        "type": "y4_status_recovery",
        "progress": _progress_bucket(state),
        "subgraph_mode": "none",  # signals GraphQAMiniDataset to skip graph
    }




def _flatten_pairs(states: list, allowed_types=None) -> List[dict]:
    allowed_types = set(allowed_types) if allowed_types else None
    all_pairs = []
    for state in states:
        bucket = _progress_bucket(state)
        for q in state.get("questions", []):
            if allowed_types is not None and q.get("type") not in allowed_types:
                continue
            meta = q.get("meta") if isinstance(q.get("meta"), dict) else {}
            base_completed = list(state.get("completed_steps", []) or [])
            completed_override = meta.get("completed_steps_override")
            rendered_completed = (
                list(completed_override)
                if isinstance(completed_override, list)
                else base_completed
            )
            pair = {
                "task_name": state["task_name"],
                "current_step": state["current_step"],
                "completed_steps": rendered_completed,
                "base_completed_steps": base_completed,
                "question": q["question"],
                "options": q.get("options") or [],
                "answer": q.get("answer"),
                "type": q["type"],
                "progress": bucket,
            }
            for field in (
                "tuple_id",
                "hypothetical_done",
                "paired_type",
                "paired_target_after",
            ):
                if meta.get(field) is not None:
                    pair[field] = meta[field]
            if q.get("answer_text"):
                pair["answer_text"] = q["answer_text"]
            if q.get("reasoning"):
                pair["reasoning"] = q["reasoning"]
            all_pairs.append(pair)
        # Synthesize y4_status_recovery items on the fly from state annotations.
        # These require no pre-built QA JSON questions — only completed_steps /
        # current_step, which every state dict already carries.
        if allowed_types is None or "y4_status_recovery" in allowed_types:
            all_pairs.append(_build_none_item(state))
    return all_pairs


def _sha256_file(path: str) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for block in iter(lambda: handle.read(4 * 1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _sha256_text(value: str) -> str:
    return hashlib.sha256(str(value).encode("utf-8")).hexdigest()


def _manifest_payload_sha256(document: dict) -> str:
    payload = dict(document)
    payload.pop("manifest_sha256", None)
    canonical = json.dumps(
        payload, ensure_ascii=False, separators=(",", ":"), sort_keys=True
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _pick_frozen_manifest_pairs(
    states: list,
    *,
    allowed_types,
    manifest_path: str,
    qa_source_path: str,
    total_qa_budget: int,
    base_seed: int,
    epoch: int,
) -> List[dict]:
    document = json.loads(Path(manifest_path).read_text(encoding="utf-8"))
    if document.get("schema") != "dlv3_control_manifest.v1":
        raise RuntimeError("unsupported QA sample manifest schema")
    expected_hash = str(document.get("manifest_sha256") or "")
    actual_hash = _manifest_payload_sha256(document)
    if not expected_hash or expected_hash != actual_hash:
        raise RuntimeError(
            f"QA sample manifest hash mismatch: {actual_hash} != {expected_hash}"
        )
    if int(document.get("seed", -1)) != int(base_seed):
        raise RuntimeError(
            f"QA sample manifest seed={document.get('seed')} != {base_seed}"
        )
    source_hash = _sha256_file(qa_source_path)
    if document.get("qa_source_sha256") != source_hash:
        raise RuntimeError("QA sample manifest source JSON hash mismatch")
    slots = (document.get("epochs") or {}).get(str(epoch))
    if not isinstance(slots, list):
        raise RuntimeError(f"QA sample manifest has no epoch {epoch}")
    if len(slots) != int(total_qa_budget):
        raise RuntimeError(
            f"QA sample manifest epoch {epoch} budget={len(slots)} "
            f"!= {total_qa_budget}"
        )
    allowed = sorted(set(allowed_types or []))
    if len(allowed) != 1:
        raise RuntimeError(
            "frozen control manifest requires exactly one QA_TYPES arm"
        )
    qtype = allowed[0]
    if qtype not in {
        "next-action-apa",
        "updated-state-apa",
        "counterfactual-unlock",
    }:
        raise RuntimeError(f"unsupported frozen-manifest QA arm: {qtype}")
    pairs = _flatten_pairs(states, allowed_types={qtype})
    by_tuple: Dict[str, dict] = {}
    for pair in pairs:
        tuple_id = str(pair.get("tuple_id") or "")
        if not tuple_id:
            continue
        if tuple_id in by_tuple:
            raise RuntimeError(f"duplicate {qtype} tuple_id: {tuple_id}")
        by_tuple[tuple_id] = pair

    selected: List[dict] = []
    for slot_index, slot in enumerate(slots):
        tuple_id = str(slot.get("tuple_id") or "")
        pair = by_tuple.get(tuple_id)
        if pair is None:
            raise RuntimeError(
                f"manifest tuple missing for {qtype}: {tuple_id}"
            )
        answer_spec = (slot.get("answers") or {}).get(qtype)
        if not isinstance(answer_spec, dict):
            raise RuntimeError(f"manifest answer missing for {qtype}: {tuple_id}")
        answer_text = str(pair.get("answer_text") or "")
        if _sha256_text(answer_text) != answer_spec.get("sha256"):
            raise RuntimeError(f"manifest answer hash mismatch: {tuple_id}/{qtype}")
        selected_pair = dict(pair)
        selected_pair["manifest_slot"] = slot_index
        selected_pair["manifest_sha256"] = expected_hash
        selected_pair["manifest_answer_tokens"] = int(answer_spec["tokens"])
        selected.append(selected_pair)
    return selected


def _weighted_type_quota(types: List[str], n: int, rng: random.Random, type_weights=None, mandatory_types=None) -> Dict[str, int]:
    type_weights = type_weights or TYPE_WEIGHTS
    mandatory_types = list(mandatory_types or MANDATORY_DECISION_TYPES)
    present = [t for t in type_weights if t in types]
    remaining = [t for t in sorted(set(types)) if t not in type_weights]
    ordered = present + remaining
    if not ordered or n <= 0:
        return {}

    weights = {t: type_weights.get(t, 0.01) for t in ordered}
    total_w = sum(weights.values()) or 1.0
    ideal = {t: n * weights[t] / total_w for t in ordered}

    # Stochastic rounding preserves the target proportions across tasks. This is
    # important for fixed eval, where each task may only receive about a dozen
    # QA items; deterministic floors would erase the 5% perception probes, while
    # forcing every type per task would greatly over-sample them.
    quota = {}
    for t in ordered:
        base = int(ideal[t])
        quota[t] = base + int(rng.random() < (ideal[t] - base))

    # If budget permits, ensure the decision-critical skills are represented.
    # Do not force low-alignment probes such as thread_of into every task.
    if n >= len(mandatory_types):
        for t in mandatory_types:
            if t in quota:
                quota[t] = max(1, quota[t])

    used = sum(quota.values())
    while used < n:
        ranked = sorted(ordered, key=lambda t: (ideal[t] - quota.get(t, 0), weights[t]), reverse=True)
        quota[ranked[0]] += 1
        used += 1

    while used > n:
        ranked = sorted(ordered, key=lambda t: (quota.get(t, 0) - ideal[t], -weights[t]), reverse=True)
        removed = False
        for t in ranked:
            min_keep = 1 if (n >= len(mandatory_types) and t in mandatory_types) else 0
            if quota.get(t, 0) > min_keep:
                quota[t] -= 1
                used -= 1
                removed = True
                break
        if not removed:
            break
    return quota


def _pick_qa_pairs(states: list, n: int, rng: random.Random, type_balance: bool = True, allowed_types=None, type_weights=None, mandatory_types=None) -> List[dict]:
    """Pick n QA pairs with type weighting and progress diversification.

    For policy-only QA, some tasks have fewer parallel-policy questions than
    their task-stratified quota. Fill the requested budget from the available
    policy pool, and if a tiny split still runs short, sample with replacement.
    """
    all_pairs = _flatten_pairs(states, allowed_types=allowed_types)
    if not all_pairs or n <= 0:
        return []
    if not type_balance:
        if len(all_pairs) >= n:
            return rng.sample(all_pairs, n)
        return [rng.choice(all_pairs) for _ in range(n)]

    by_type: Dict[str, list] = defaultdict(list)
    for pair in all_pairs:
        by_type[pair["type"]].append(pair)
    for pool in by_type.values():
        rng.shuffle(pool)

    if type_weights and "parallel_robot_action" in type_weights:
        non_policy = sorted(t for t in by_type if t != "parallel_robot_action")
        if non_policy and type_weights.get("parallel_robot_action", 0) >= 1.0:
            # Keep policy-heavy mixed at 50% policy and split the rest across
            # the non-policy types actually present in the QA file.
            type_weights = {"parallel_robot_action": 1.0, **{t: 1.0 / len(non_policy) for t in non_policy}}

    quotas = _weighted_type_quota(list(by_type), n, rng, type_weights=type_weights, mandatory_types=mandatory_types)
    selected = []
    selected_ids = set()

    # Round-robin within each type by progress bucket, so one task does not only
    # contribute early trivial states.
    for qtype, quota in quotas.items():
        pool = by_type.get(qtype, [])
        if not pool or quota <= 0:
            continue
        by_progress: Dict[str, list] = defaultdict(list)
        for p in pool:
            by_progress[p.get("progress", "mid")].append(p)
        progress_order = ["early", "mid", "late"]
        cursor = 0
        while quota > 0 and any(by_progress.values()):
            bucket = progress_order[cursor % len(progress_order)]
            cursor += 1
            if not by_progress[bucket]:
                continue
            p = by_progress[bucket].pop()
            pid = id(p)
            if pid in selected_ids:
                continue
            selected.append(p)
            selected_ids.add(pid)
            quota -= 1

    if len(selected) < n:
        leftover = [p for p in all_pairs if id(p) not in selected_ids]
        rng.shuffle(leftover)
        take = min(n - len(selected), len(leftover))
        selected.extend(leftover[:take])
        selected_ids.update(id(p) for p in leftover[:take])

    if len(selected) < n:
        selected.extend(rng.choice(all_pairs) for _ in range(n - len(selected)))

    rng.shuffle(selected)
    return selected[:n]


def sample_qa_for_epoch(
    qa_data: list,
    e2e_task_counts: Dict[str, int],
    total_qa_budget: int,
    min_per_task: int = 4,
    base_seed: int = 42,
    epoch: int = 0,
    sampling_mode: str = "parallel_policy_only",
    sample_manifest: str = "",
    qa_source_path: str = "",
) -> List[dict]:
    """Sample QA pairs for one epoch."""
    rng = random.Random(base_seed + epoch * 1000)
    mode, allowed_types, type_weights, mandatory_types = _mode_config(sampling_mode)
    if sample_manifest:
        if mode != "dlv3_yaml":
            raise RuntimeError("QA sample manifest requires dlv3_yaml mode")
        if not qa_source_path:
            raise RuntimeError("QA sample manifest requires qa_source_path")
        return _pick_frozen_manifest_pairs(
            qa_data,
            allowed_types=allowed_types,
            manifest_path=sample_manifest,
            qa_source_path=qa_source_path,
            total_qa_budget=total_qa_budget,
            base_seed=base_seed,
            epoch=epoch,
        )
    by_task = _group_qa_by_task(qa_data)
    all_tasks = sorted(set(by_task.keys()) | set(e2e_task_counts.keys()))

    if mode in {"uniform", "uniform_all", "uniform_all_types", "all_uniform", "policy_heavy_mixed"}:
        all_states = [state for states in by_task.values() for state in states]
        return _pick_qa_pairs(
            all_states, total_qa_budget, rng, type_balance=True,
            allowed_types=allowed_types,
            type_weights=type_weights,
            mandatory_types=mandatory_types,
        )

    guaranteed = min_per_task * len(all_tasks)
    remaining = max(0, total_qa_budget - guaranteed)
    total_e2e = sum(e2e_task_counts.values()) or 1

    task_budgets: Dict[str, int] = {}
    for task in all_tasks:
        base = min_per_task
        prop = int(remaining * e2e_task_counts.get(task, 0) / total_e2e)
        task_budgets[task] = base + prop

    used = sum(task_budgets.values())
    diff = total_qa_budget - used
    if diff > 0 and all_tasks:
        top_tasks = sorted(all_tasks, key=lambda t: e2e_task_counts.get(t, 0), reverse=True)
        for i in range(diff):
            task_budgets[top_tasks[i % len(top_tasks)]] += 1

    result = []
    for task in all_tasks:
        states = by_task.get(task, [])
        if not states:
            continue
        n = task_budgets.get(task, min_per_task)
        result.extend(_pick_qa_pairs(states, n, rng, type_balance=True, allowed_types=allowed_types, type_weights=type_weights, mandatory_types=mandatory_types))

    if len(result) < total_qa_budget:
        all_states = [state for states in by_task.values() for state in states]
        result.extend(_pick_qa_pairs(all_states, total_qa_budget - len(result), rng, type_balance=True, allowed_types=allowed_types, type_weights=type_weights, mandatory_types=mandatory_types))

    rng.shuffle(result)
    return result[:total_qa_budget]


def build_fixed_eval_qa(qa_test_data: list, total: int = 1000, seed: int = 12345, sampling_mode: str = "parallel_policy_only") -> List[dict]:
    """Build a fixed QA eval set, task-balanced, from test data."""
    rng = random.Random(seed)
    mode, allowed_types, type_weights, mandatory_types = _mode_config(sampling_mode)
    by_task = _group_qa_by_task(qa_test_data)
    all_tasks = sorted(by_task.keys())
    if not all_tasks:
        return []

    if mode in {"uniform", "uniform_all", "uniform_all_types", "all_uniform", "policy_heavy_mixed"}:
        all_states = [state for states in by_task.values() for state in states]
        return _pick_qa_pairs(
            all_states, total, rng, type_balance=True,
            allowed_types=allowed_types,
            type_weights=type_weights,
            mandatory_types=mandatory_types,
        )

    per_task = max(1, total // len(all_tasks))
    result = []
    for task in all_tasks:
        states = by_task[task]
        result.extend(_pick_qa_pairs(states, per_task, rng, type_balance=True, allowed_types=allowed_types, type_weights=type_weights, mandatory_types=mandatory_types))

    if len(result) < total:
        all_states = [state for states in by_task.values() for state in states]
        result.extend(_pick_qa_pairs(all_states, total - len(result), rng, type_balance=True, allowed_types=allowed_types, type_weights=type_weights, mandatory_types=mandatory_types))

    rng.shuffle(result)
    return result[:total]
